### ISSUE TITLE
Long contributors names

### ISSUE THREAD

**Issue by jtemporal** [okfn-brasil/serenata-website#13]
So now we have the contributors names on the about page. One problem is that some of the names are very long and they break to fit inside the column space as we can see in the picture bellow:

![screenshot from 2017-02-02 11-09-44](https://cloud.githubusercontent.com/assets/6595551/22550640/2f8e9430-e938-11e6-9cb4-c23f9a4d9c26.png)

that makes the column end in different heights as we can see in this other image:

![screenshot from 2017-02-02 11-11-44](https://cloud.githubusercontent.com/assets/6595551/22550696/6770701c-e938-11e6-80fd-bcd99857ce93.png)

Any ideas on how to fix this little bug?

cc @anaschwendler

**Comment by idmarjr** [comment]
@jtemporal Can you provide a link to the file that have this markup? :)

**Comment by cuducos** [comment]
@idmarjr [here](https://github.com/datasciencebr/serenata-website/blob/master/about.html) it is ; )

**Comment by leomeloxp** [comment]
There are 2 ways I can see for fixing this, depending on desired outcome.

First would be to have each contributor name being wrapped with a `col-md-4`, the outcome of that would be:
```html
<div class="col-md-12 p-0">
  <div class="row">
    <p class="col-md-4">Abelardo Vieira Mota</p>
    ...
  </div>
</div>
```
![screen shot 2017-02-02 at 14 52 33](https://cloud.githubusercontent.com/assets/266852/22554394/c1a00f4c-e957-11e6-92b7-7a75b70cb082.png)

The other, and simpler approach would be to have the wrapping div with a 12 width and add `column-count: 3` as style. The result of that one would be:
```html
<div class="col-md-12 p-0" style="column-count: 3;">
  <p>Abelardo Vieira Mota</p>
  ...
</div>
```
![screen shot 2017-02-02 at 14 53 12](https://cloud.githubusercontent.com/assets/266852/22554524/44f683ee-e958-11e6-961c-94933e6ecd8d.png)

I did this very quickly whilst at work so some further testing would be necessary. Just thought it would be worth mentioning 🙂

**Comment by idmarjr** [comment]
Questions:
1. Is it mandatory to organize alphabetically based in the columns? (From top to bottom);
2. Any specific browser support needed?

I'm asking it for two reasons:
1. If alphabetical organization by columns isn't a need I will suggest to use a `<ul>` to organize names and float itens with `min-height`. Not the most flexible solution but it will work
2. Flexbox is an option to work on it but [IE doesn't deal perfectly with it](http://caniuse.com/#feat=flexbox);

**Comment by jtemporal** [comment]
@idmarjr

> 1. Is it mandatory to organize alphabetically based in the columns? (From top to bottom);

 It is **not** but is something that I would like to keep. It gives the idea of mental organization to the reader. Also, it gives the brain a clear pattern without it having to figure one out ;P

> 2. Any specific browser support needed?

Not really but, it would be nice if the site would not break on the most used browsers. ;)

@leomeloxp I really like the second idea there! It looks like something that we discussed about earlier today :)

Thanks guys for the ideas!!! You are all awesome ;)

**Comment by cuducos** [comment]
> Is it mandatory to organize alphabetically based in the columns? (From top to bottom);

No need, I guess. It could be alphabetically in the row direction (as a result of the `float`), that would still have an ordering for the brain — brains are good in recognizing patterns ; )

> Any specific browser support needed?

Current minus two. IE 9 is dead.

**Comment by cuducos** [comment]
I thought I have added a comment regarding `flexbox`, but I can't find it. So I'm commenting again. Maybe `space-between` (in the rows) and `stretch` (in the columns) can fix it. Haven't tested though.

**Comment by anaschwendler** [comment]
@Irio solved the case gracefully.
