### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by mariovalney** [okfn-brasil/serenata-website#16]
Everything is broken to down of 1247px.
Maybe the only necessary by now is some adjustments to adapt the current content including menu and a version of the main image in a vertical organization.

**Comment by anaschwendler** [comment]
Hello @mariovalney!
So, it was my job doing that, and i'll be focusing on that by today.

Last week we got into another things so i couldn't focus on that :)
Thanks for the tips, soon it will be fixed!

**Comment by anaschwendler** [comment]
Ok, discussing in our telegram group we concluded that there is another things that I need to focus.
We're doing some new investigations and I can be more useful solving that.

The question is: there is someone that could help us with that?

**Comment by evertonl1ma** [comment]
Peguei o projeto para terminar, e irei fazer a parte de transformá-lo em responsivo.

**Comment by anaschwendler** [comment]
Thanks to @evertonl1ma this issue is solved!
Our website is mobile responsive now :)
