### ISSUE TITLE
Add apoia.se supporters

### ISSUE THREAD

**Issue by jtemporal** [okfn-brasil/serenata-website#18]
now we have a scrapping app for the apoia.se supporters:

https://github.com/datasciencebr/auditorium/

we need to use it \o/

**Comment by anaschwendler** [comment]
apoia.se is being reestructured by now, and doesn't have a way to fetch automatically its supporters, filtering by privacy, and the plataform is not prepared to do that yet, and they say that there is a lot work to be done.

we will have to wait until they have this feature implemented again.

**Comment by Irio** [comment]
Just sent an email to all the supporters, asking if they want to have their name published.

**Comment by Irio** [comment]
Contributors had a week to answer the email and we adding as we get more answers. Closing since it's not a real issue anymore.
