### ISSUE TITLE
Telegram group link

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/serenata-website#2]
The link is not available anymore in the new `README.md` and not available in our website either.

**Comment by cuducos** [comment]
I mean… it's there. But kind of hidden (you have to click on something to make Ctrl+F find it).

**Comment by mariovalney** [comment]
I was able to find the link in FAQ: https://serenatadeamor.org/faq/

Where should we put it? Maybe in footer?

**Comment by cuducos** [comment]
@mariovalney this issue is _old_… I think that — as the Telegram group is focused on the tech community — we can close this issue: the link for the Telegram group is in the [first lines of our contributing guide](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md), that's enough IMHO.
