### ISSUE TITLE
Update Gemfile.lock

### ISSUE THREAD

**Issue by jtemporal** [okfn-brasil/serenata-website#33]
Our Gemfile.lock is outdated (e.g. `jekyll` is already on version 3.5).

tip: Run `bundle update` to generate the new file

**Comment by cuducos** [comment]
> Our Gemfile.lock is outdated

Does it worth it to use this tool https://gemnasium.com/ ?

**Comment by jtemporal** [comment]
>Does it worth it to use this tool https://gemnasium.com/ ?

maybe a good thing to take a look into it. I only found out that the file was outdated by accident.

cc @cuducos
