### ISSUE TITLE
Mention @RosiaDaSerenata

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/serenata-website#37]
As [suggested on Twitter](https://twitter.com/JV_Schiavo/status/910917522991525889) we could mention and Link Rosie's Twitter account in the website.

**Comment by arioston** [comment]
Hi,
What do you think about change the text :

"A Operação Serenata de Amor criou um Robô - uma inteligência artificial capaz de analisar cada pedido de reembolso dos deputados e identificar a probabilidade de ilegalidade."

to :

"A Operação Serenata de Amor criou a [Rosie](https://twitter.com/RosieDaSerenata) - uma inteligência artificial capaz de analisar cada pedido de reembolso dos deputados e identificar a probabilidade de ilegalidade."

This change will make two things , first this will make a mention to Rosie and second the word "Robo" is harsh, Rosie more pleasant.
Last but not least, sorry for any mistakes. English is not my native language".

**Comment by cuducos** [comment]
Actually we like calling her a robot, but I do like your suggestion!

**Comment by jtemporal** [comment]
> Actually we like calling her a robot, but I do like your suggestion!
+1

my two cents: she is indeed a robot, but the change in text helps create idea of Rosie as a persona.

**Comment by arioston** [comment]
sorry about the commit, I am very inexperienced with git and I made some mistakes. 
About the message here is the change :

![image](https://user-images.githubusercontent.com/6132300/31210605-c5100326-a969-11e7-8404-3ce40e2979e7.png)

if you allow me to make the change, the color should be black or purple is better?

**Comment by cuducos** [comment]
> About the message here is the change

I like it _ and I like the color too : )

**Comment by idmarjr** [comment]
I think this issue is already solved, am I right?

**Comment by cuducos** [comment]
Ooops, yep, it is!
