### ISSUE TITLE
Show Digital Ocean as sponsor

### ISSUE THREAD

**Issue by Irio** [okfn-brasil/serenata-website#4]
They've been providing Jarbas' server https://github.com/datasciencebr/jarbas.

Where and how to put the logo? No idea. Open for suggestions.

**Comment by cuducos** [comment]
We discussed that earlier today (@anaschwendler, @anacarlotajahn, @filipelinhares and me) and this is a thing for the newer version of the website. It doesn't worth it to just improvise something in the layout to last a few days.

**Comment by jtemporal** [comment]
@brunopazzim Hey any idea how to fit this in the website?! =)

**Comment by cuducos** [comment]
@brunopazzim just in case https://www.digitalocean.com/company/logos-and-badges/

**Comment by anaschwendler** [comment]
its already done, i think o.õ

![image](https://cloud.githubusercontent.com/assets/4131432/22907359/d7e1cde6-f22f-11e6-9154-1f8a16e04268.png)

close the case?
