### ISSUE TITLE
New website: reading

### ISSUE THREAD

**Issue by anaschwendler** [okfn-brasil/serenata-website#45]
[WIP description]

Following the new website issue, we have a new page ready to be coded. Until now, @thulioph has started home, as we see at #43 and #44 and is planning the base for the website.

The layout:
https://drive.google.com/file/d/1nMn9Y-OU-Fp9sZadpnpm-UlQUfFfFm6g/view?usp=sharing

With format informations:
https://drive.google.com/file/d/1U_3_Mu1qmxMsodn6J_7Dp5CtVEUCRxDK/view?usp=sharing

And some @tatianasb recomendations:

Could you please, on the upper menu, maintain as standard fonts:
Roboto, Regular, 20 pt - the non selected option
Roboto, Bold, 20 pt - for the selection option (the last one was Roboto, BLACK, 20pt)

Let’s try to stick with two fonts for now:
Roboto Regular & Roboto Bold

**Comment by thulioph** [comment]
Hey @anaschwendler, can you share what colors are used? If you have the hex value, it's better.

**Comment by cuducos** [comment]
| Semantic name | RGB | Examples of usage |
|-----|-----|-----|
| Pink | 215, 0, 161 | Headings, Icons, horizontal rules |
| Primary purple | 102, 51, 153 | Header icons |
| Secondary purple | 137, 0, 161 | Menu background |
| Dark gray | 63, 63, 63 | Text |
| White | 255, 255, 255 | Background, text and elements over purple background |

**Comment by anaschwendler** [comment]
> Hey @anaschwendler, can you share what colors are used?

@tatianasb have those infos, thanks @cuducos for doing that <3

**Comment by cuducos** [comment]
Closed by inactivity.
