### ISSUE TITLE
New website: blog post

### ISSUE THREAD

**Issue by anaschwendler** [okfn-brasil/serenata-website#46]
Medium wants its content to be paid, and we want to separate datasciencebr and serenata content we will be adding the posts to our own blog.

The layout:
https://drive.google.com/file/d/1A4Jsl6ocBGXpDp3qh2QQTgjrlGI507ye/view?usp=sharing

With format informations:
https://drive.google.com/file/d/1ib3I41qVOQyD8d0H3mhtLIwF52VUCUpe/view?usp=sharing

So, how we will work: until we do not have our content in our own blog we will be using the medium script to get the posts. When finished, the idea is to list the posts in our blog, we will (or not) replicate in the medium, but the idea is to keep them in our website

**Comment by cuducos** [comment]
Closed by inactivity.
