### ISSUE TITLE
FAQ links are not working

### ISSUE THREAD

**Issue by jeancsil** [okfn-brasil/serenata-website#5]
When trying to see all the FAQ links, clicking in the anchors didn't show the content.
I'm using chrome and MacOS.

**Comment by jeancsil** [comment]
BTW the chrome version is: 54.0.2840.71 (64-bit)

**Comment by filipelinhares** [comment]
Thanks for your report @jeancsil! I'm fixing that.

**Comment by jeancsil** [comment]
Nice Filipe!
Thanks.

**Comment by filipelinhares** [comment]
Done: 120cdbe6ed7a50ee52db9916e89bd2fdaf62aac5
