### ISSUE TITLE
Data Science Brigade URL on footer not working

### ISSUE THREAD

**Issue by mvinoba** [okfn-brasil/serenata-website#55]
The Data Science Brigade image on footer links to https://datasciencebr.com/contrate-especialistas-3b0b025d3bd1#.jylbm96ig , it looks like it was supposed to link to this article: https://medium.com/data-science-brigade/contrate-especialistas-3b0b025d3bd1, but I'm not sure enough to commit the fix and open a PR, since DataScienceBrigade has [a webpage](https://datasciencebr.com/
).

**Comment by cuducos** [comment]
Many thanks, @mvinoba – I suggested linking to their homepage in #57
