### ISSUE TITLE
Update info about funding on the website

### ISSUE THREAD

**Issue by fgrehm** [okfn-brasil/serenata-website#6]
<img width="541" alt="screen shot 2016-12-13 at 10 50 17 am" src="https://cloud.githubusercontent.com/assets/81859/21140995/ef5a7d2c-c121-11e6-82f4-86ddced97364.png">

I think the "crowdfunding wording" on the website should be updated with some info about the campaign being over and could add the PayPal / Bitcoin donation links in the same spirit of https://github.com/datasciencebr/serenata-de-amor/pull/166

**Comment by anaschwendler** [comment]
Thanks @fgrehm for the advise, now everything it's fine and published :)
we can check at: https://serenatadeamor.org/

🎉
