### ISSUE TITLE
Hover area on footer anchor tag

### ISSUE THREAD

**Issue by lucasdutraf** [okfn-brasil/serenata-website#60]
**What is the problem?**
The hover area on the footer anchor tag is much bigger than the actual text width as the following video shows:

![toreproduce](https://user-images.githubusercontent.com/31940073/49681637-847dc300-fa8c-11e8-9b0d-f1edea7f4492.gif)

A expected behaviour can be seen in github:

![expected](https://user-images.githubusercontent.com/31940073/49681623-47193580-fa8c-11e8-9015-854bf058a001.gif)

**How can this be addressed?**
Adjust the text hover area to match the text width, instead of matching the div width. 

**Who could help with this issue?**
@youssef-md

**Labels**
[UI&UX]  [bug]

@RochaCarla

**Comment by youssef-md** [comment]
The footer area need a general refactoring and enhancement, to improve the maintainability and the responsiveness, this contribution can be the start of a relashionship with the project.

**Comment by cuducos** [comment]
Closed by #61
