### ISSUE TITLE
HTTPS brakes AJAX

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/serenata-website#9]
As we load Medium posts via AJAX, _if_ user access the website using HTTPS, for security reasons AJAX will fail in requesting contents via HTTP.

* Either we disable HTTPS in GitHub pages (not sure if it is possible), as we don't collect data, that is not a major problem
* Or we implement HTTP in our Medium proxy ([this](https://github.com/substrakt/letsencrypt-heroku) or [this](https://devcenter.heroku.com/articles/ssl) might be helpful)

**Comment by mariovalney** [comment]
Is it still valid? I wasn't able to find the problem.

**Comment by cuducos** [comment]
> Is it still valid? I wasn't able to find the problem.

Yay… you're right, @mariovalney! Many tks.
